services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 9090:80  
    environment:
      PMA_ARBITRARY: 1  
    depends_on:
      - db 
  
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: db
    ports:
      - 3306:3306  
    environment:
      MYSQL_ROOT_PASSWORD: qwerty  
      MYSQL_DATABASE: proyecto  
      MYSQL_USER: admin  
      MYSQL_PASSWORD: admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

  back-empresa:
    build:
      context: ./registro-empresas
    container_name: back-empresa
    depends_on:
      - db
    ports:
      - 3003:3003
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 350M
        reservations:
          cpus: '0.20'
          memory: 250M

  back-vuelos:
    build:
      context: ./calendario-vuelos
    container_name: back-vuelos
    depends_on:
      - db
    ports:
      - 3002:3002
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 350M
        reservations:
          cpus: '0.20'
          memory: 250M
  
  front:
    build:
      context: ./angular-main
    container_name: front
    depends_on:
      - back-vuelos
      - back-empresa
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 300M
        reservations:
          cpus: '0.15'
          memory: 200M